name: Greeter
description: Greeter indexer
networks:
  - id: 137 # Polygon
    start_block: 45336336
    contracts:
      - name: PolygonGreeter
        abi_file_path: abis/greeter-abi.json
        address: "0x9D02A17dE4E68545d3a58D3a20BbBE0399E05c9c"
        handler: src/EventHandlers.ts
        events:
          - event: "NewGreeting"
            requiredEntities:
              - name: "Greeting"
          - event: "ClearGreeting"
            requiredEntities:
              - name: "Greeting"
  - id: 59144 # Linea
    start_block: 367800
    contracts:
      - name: LineaGreeter
        abi_file_path: abis/greeter-abi.json
        address: "0xdEe21B97AB77a16B4b236F952e586cf8408CF32A"
        handler: ./src/EventHandlers.ts
        events:
          - event: "NewGreeting"
            requiredEntities:
              - name: "Greeting"
          - event: "ClearGreeting"
            requiredEntities:
              - name: "Greeting"
