name: Poolfish V3 indexer
description: An indexer to index multiple networks and multiple contracts from pools tracked on Poolfish
contracts:
  - name: Factory
    handler: src/FactoryEventHandlers.ts
    events:
      - event: "PoolCreated(address indexed token0, address indexed token1, uint24 indexed fee, int24 tickSpacing, address pool)"
        isAsync: true
      - event: "OwnerChanged(address indexed oldOwner, address indexed newOwner)"
  - name: Pool
    handler: src/PoolEventHandlers.ts
    events:
      - event: "Initialize(uint160 sqrtPriceX96, int24 tick)"
        isAsync: true        
      - event: "Mint(address sender, address indexed owner, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount, uint256 amount0, uint256 amount1)"        
        isAsync: true
      - event: "Burn(address indexed owner, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount, uint256 amount0, uint256 amount1)"
        isAsync: true
      - event: "Swap(address indexed sender, address indexed recipient, int256 amount0, int256 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick)"
        isAsync: true
networks:
  - id: 1 # Ethereum
    start_block: 0
    contracts:
      - name: Factory
        address:
          # - "0x1F98431c8aD98523631AE4a59f267346ea31F984" # uniswap
          # - "0x0bfbcf9fa4f9c56b0f40a671ad40e0805a091865" # pancakeswap
          - "0xbaceb8ec6b9355dfc0269c18bac9d6e2bdc29c4f" # sushi
      - name: Pool
  # - id: 137 # Polygon
  #   start_block: 41024971 # The deployment block https://polygonscan.com/address/0x917933899c6a5F8E37F31E19f92CdBFF7e8FF0e2
  #   contracts:
  #     - name: Factory
  #       address: "0x917933899c6a5F8E37F31E19f92CdBFF7e8FF0e2"
  #     - name: Pool  
  # - id: 100 # Gnosis
  #   start_block: 27232871 # The deployment block https://gnosisscan.io/address/0xf78031CBCA409F2FB6876BDFDBc1b2df24cF9bEf
  #   contracts:
  #     - name: Factory
  #       address: "0xf78031CBCA409F2FB6876BDFDBc1b2df24cF9bEf"
  #     - name: Pool  
  # - id: 56 # BSC
  #   start_block: 26956207 # The deployment block https://bscscan.com/txs?a=0x0bfbcf9fa4f9c56b0f40a671ad40e0805a091865
  #   contracts:
  #     - name: Factory
  #       address:
  #         - "0xdB1d10011AD0Ff90774D0C6Bb92e5C5c8b4461F7" # uniswap
  #         # - "0x0bfbcf9fa4f9c56b0f40a671ad40e0805a091865" # pancakeswap
  #     - name: Pool  
