name: Poolfish indexer
description: An indexer to index multiple networks and multiple contracts from pools tracked on Poolfish
networks:
  - id: 137 # Polygon
    start_block: 41024971 # The deployment block https://polygonscan.com/address/0x917933899c6a5F8E37F31E19f92CdBFF7e8FF0e2
    contracts:
      - name: UniV3Factory
        address: "0x917933899c6a5F8E37F31E19f92CdBFF7e8FF0e2"
        handler: src/EventHandlers.ts
        events:
          - event: "event OwnerChanged(address indexed oldOwner, address indexed newOwner)"
            requiredEntities:
              - name: "Factory"
